# Generated by Django 4.2.5 on 2023-10-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_blogdal_delete_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdal',
            options={'managed': False},
        ),
    ]
