# Generated by Django 4.2.5 on 2023-10-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_blogdal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdal',
            options={},
        ),
    ]
