# Generated by Django 4.2.5 on 2023-10-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_blogdal_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogDAL',
            new_name='BlogModel',
        ),
    ]
